#######################################################################
#### QUINOA ####
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=18.18.0

#######################################################################
#### POSTGRESQL ####
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username=goaliemasterowner
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/goaliemaster

#######################################################################
#### HIBERNATE ####
quarkus.hibernate-orm.database.generation=drop-and-create

#######################################################################
#### SMALLRYE ####
smallrye.jwt.sign.key.location=keys/privateKey.pem
mp.jwt.verify.issuer=goalie-master-backend
mp.jwt.verify.publickey.location=keys/publicKey.pem